- platform: mqtt
  name: "Cabinet LEDs"
  command_topic: "hass/mqttstrip/setpower"
  state_topic: "hass/mqttstrip/setpowerpub"
  rgb_state_topic: "hass/mqttstrip/setcolorpub"
  rgb_command_topic: "hass/mqttstrip/setcolor"
  brightness_state_topic: "hass/mqttstrip/setbrightnesspub"
  brightness_command_topic: "hass/mqttstrip/setbrightness"
  optimistic: false
