- platform: darksky
  api_key: !secret darksky_api_key
  monitored_conditions:
    - summary
    - icon
    - temperature
    - wind_speed
    - wind_bearing
    - humidity
    - temperature_max
    - temperature_min
    - precip_probability
    - precip_intensity
    - pressure
    - apparent_temperature
- platform: buienradar
  name: "Buienradar"
  timeframe: 3600
- platform: waqi
  locations:
    - antwerp
- platform: speedtest
  server_id: 2955
  monitored_conditions:
    - ping
    - download
    - upload
- platform: template
  sensors:
    alarm_time:
      friendly_name: 'Time'
      value_template: '{{ "%0.02d:%0.02d" | format(states("input_slider.alarmhour") | int, states("input_slider.alarmminutes") | int) }}'
- platform: time_date
  display_options:
    - 'time'
    - 'date'
    - 'date_time'
    - 'time_date'
