- platform: rfxtrx
  automatic_add: True
  devices:
    0b11000000f5f11e01010f50:
      name: staande_lampen
    0b11000103bc0cfe01010f70:
      name: living_staande_lamp
    0b11000124bc0cfe03010f70:
      name: dj_staande_lamp
    0b11000622bc0cfe04010f70:
      name: eet_staande_lamp
    0b11000600f5f11e02010f50:
      name: scene1
      fire_event: True
    0b11000100f5f11e03000060:
      name: scene2
      fire_event: True
    7100a0341040000:
      name: kerst

- platform: srf
  port: /dev/ttyS0
  baudrate: 115200
  switches:
    Test:
      code: AA
      pin: '05'
      type: D
    Arduino3:
      code: AB
      pin: '03'
      type: H
- platform: wake_on_lan
  mac_address: "AC:9B:0A:EA:8D:37" #"AC-9B-0A-EA-8D-37"
  name: "TV"
