- platform: rfxtrx
  automatic_add: False
  devices:
    0b11000000f5f11e01010f50:
      name: Staande lampen
      fire_event: True
    0b11000103bc0cfe01010f70:
      name: Living staande lamp
    0b11000124bc0cfe03010f70:
      name: DJ staande lamp
    0b11000622bc0cfe04010f70:
      name: Eet staande lamp
    0b11000600f5f11e02010f50:
      name: scene1
      fire_event: True
    0b11000100f5f11e03000060:
      name: scene2
      fire_event: True
    7100a0041030000:
      name: laser
    7100a0041040000:
      name: Telenet router


- platform: srf
  port: /dev/ttyS0
  baudrate: 115200
  switches:
    Test:
      code: AA
      pin: '05'
      type: D
    Arduino3:
      code: AB
      pin: '03'
      type: H
- platform: wake_on_lan
  mac_address: "AC:9B:0A:EA:8D:37" #"AC-9B-0A-EA-8D-37"
  name: "TV"

- platform: mqtt
  name: "relay test"
  state_topic: "hass/relay/switch1"
  command_topic: "hass/relay/switch1/set"
  payload_on: "ON"
  payload_off: "OFF"
  optimistic: false
